const FRAME_RATE=100;
const GRID_X=100;
const GRID_Y=60;
const WIN_SCORE = 5;
const SPEEN_INCREMENT_FACTOR = 0.04;

export {
    FRAME_RATE,
    GRID_X,
    GRID_Y,
    WIN_SCORE,
    SPEEN_INCREMENT_FACTOR,
}